name: PR Review
on:
  pull_request:
    branches: [ main, development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check linting rules
      run: npm run ci-lint